#layout: page
title: Raghavendra Shrestha
logo: /assets/raghav_pp_1.png
baseurl: ""
url: "https://raghavshrestha.github.io/portfolio/"
call: 0412 718 345
email: raghav.shrestha@gmail.com
linkedin_username: www.linkedin.com/in/raghavendra-bahadur-shrestha-a44283115
#description: Looking for the opportunity to challenge my skills and knowledge as well as to grow in career.
#show_downloads: True
theme: jekyll-theme-minimal
